version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: recipeapp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/recipeapp
      - PORT=8080
      - JWT_SECRET=supersecret
    restart: on-failure

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL_ARG: http://localhost:8080/api
    ports:
      - "8081:80"  # Nginx serves on port 80 inside container
    environment:
      - VITE_API_URL=http://backend:8080/api
    depends_on:
      - backend

volumes:
  pgdata:
