---
# values.yaml
frontend:
  image:
    repository: your-docker-repo/frontend
    tag: latest
  replicaCount: 1

backend:
  image:
    repository: your-docker-repo/backend
    tag: latest
  replicaCount: 1
  env:
    - name: DB_HOST
      value: kulen-postgres
    - name: DB_USER
      value: user
    - name: DB_PASSWORD
      value: password
    - name: DB_NAME
      value: kulen

database:
  enabled: true
  image:
    repository: postgres
    tag: "15"
  storage:
    size: 1Gi
  credentials:
    user: user
    password: password
    database: kulen

ingress:
  enabled: true
  host: your.domain.com
  tlsSecret: recipe-tls
  className: "nginx"
  hosts:
    - host: kulen.local
      paths:
        - path: /
          pathType: Prefix

postgresql:
  storageClass: standard
  storage: 1Gi