---
# values.yaml
frontend:
  imagePullSecrets:
    - name: ghcr-secret
  image:
    repository: ghcr.io/aleksandarss/kulen/frontend
    tag: latest
  replicaCount: 1
  env:
    - name: VITE_API_URL
      value: https://kulen.mithrandir.calic.cloud/backend

backend:
  imagePullSecrets:
    - name: ghcr-secret
  image:
    repository: ghcr.io/aleksandarss/kulen/backend
    tag: latest
  replicaCount: 1
  env:
    - name: DATABASE_URL
      value: postgres://user:password@postgres:5432/recipeapp
    - name: PORT
      value: "8080"
    - name: JWT_SECRET
      value: supersecret

ingress:
  enabled: true
  issuerName: letsencrypt-http
  host: kulen.mithrandir.calic.cloud
  tlsSecret: recipe-tls
  className: "nginx"
  hosts:
    - host: kulen.mithrandir.calic.cloud
      paths:
        - path: /
          pathType: Prefix

postgres:
  enabled: true
  image: postgres:15
  user: user
  password: password
  db: recipeapp
  storage: 1Gi
  storageClass: "standard"