apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "recipe-app.fullname" . }}-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      {{- if .Values.frontend.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.frontend.imagePullSecrets | nindent 8 }}
      {{- else }}
      imagePullSecrets:
        - name: ghcr-secret
      {{- end }}
      containers:
        - name: frontend
          image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
          {{- if .Values.frontend.env }}
          env: {{ toYaml .Values.frontend.env | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: 5173
          resources: {{ toYaml .Values.frontend.resources | nindent 12 }}
