---
# templates/deployment-backend.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "recipe-app.fullname" . }}-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      {{- if .Values.backend.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.backend.imagePullSecrets | nindent 8 }}
      {{- else }}
      imagePullSecrets:
        - name: ghcr-secret
      {{- end }}

      containers:
        - name: backend
          image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
          ports:
            - containerPort: 8080
          {{- if .Values.backend.env }}
          env: {{ toYaml .Values.backend.env | nindent 12 }}
          {{- end }}
          resources: {{ toYaml .Values.backend.resources | nindent 12 }}