---
# templates/deployment-backend.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: {{ .Values.backend.imagePullSecrets | default "ghcr-secret" }}
      containers:
        - name: backend
          image: {{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag }}
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_USER
              value: {{ .Values.postgres.user }}
            - name: DB_PASSWORD
              value: {{ .Values.postgres.password }}
            - name: DB_NAME
              value: {{ .Values.postgres.db }}
          resources: {{ toYaml .Values.resources | nindent 12 }}